@startuml database
title Схема базы данных
skinparam linetype ortho

!procedure Table($name, $desc)
  class $name as "$desc" <<(T, #FFAAAA)>>
!endprocedure

!procedure primary_key($name)
  <b>$name</b>: integer <b>PK</b>
!endprocedure

!procedure foreign_key($name)
  <i>$name</i>: integer NOT NULL <b>Foreing key</b>
!endprocedure

!procedure not_null($name, $type="integer")
  $name: $type NOT NULL
!endprocedure


Table(Task, "Программы\n  для устройсва") {
  primary_key(id)
  not_null("name", "varchar(255)")
  not_null("description", "varchar(255)") default ""
}

Table(TaskItem, "Задачи программы") {
  primary_key(id)
  foreign_key(task_id)
  foreign_key(task_item_id)
}

Table(TaskItemType, "Тип задачи") {
  primary_key(id)
  not_null("name", "varchar(255)")
}

Task ||-right-|{ TaskItem
TaskItemType ||-left-|{ TaskItem

' e01 ||..o{ e02
' e01 |o..o{ e03
@enduml